# Generated by Django 5.1.4 on 2024-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('coi', models.FloatField(max_length=10)),
                ('ri', models.FloatField(max_length=10)),
                ('coipri', models.FloatField(max_length=10)),
                ('gi', models.FloatField(max_length=10)),
                ('lppi', models.FloatField(max_length=10)),
            ],
        ),
    ]
